/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
    id("java-library")
    id("maven-publish")
}

group = "org.rwiuff"
version = "1.0"

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

publishing {
    publications {
        create<MavenPublication>("SteelBrew") {
            artifactId = "steelbrew"
            from(components["java"])
            versionMapping {
                usage("java-api") {
                    fromResolutionOf("runtimeClasspath")
                }
                usage("java-runtime") {
                    fromResolutionResult()
                }
            }
            pom {
                name = "SteelBrew"
                description = "A testing framework for verifying chips in Java"
                developers {
                    developer {
                        id = "rwiuff"
                        name = "Rasmus Wiuff"
                        email = "rwiuff@gmail.com"
                    }
                }
            }
            withBuildIdentifier()
        }
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    // maven {
    //     name = "myRepo"
    //     url = uri(layout.buildDirectory.dir("repo"))
    // }
}
